#Shutter main window
panelShutter=Shutter Encoder

#grpChooseFiles
grpChooseFiles=Valitse tiedostot
btnBrowse=Selaa...
btnEmptyList=Tyhjennä
btnReset=Palauta
lblTermine=0 Valmistunut
fileEnded=Valmistunut
filesEnded=Valmistunut
import=Tuo kohteita
file=Tiedosto
files=Tiedostot
dropFilesHere=Pudota tiedostot tähän
filesVideoOrAudio=Video- tai äänitiedosto(t)
fileVideoAndAudio=Videotiedosto ja äänitiedosto(t)
filesVideoOrAudioOrPicture=Video-, ääni- tai kuvatiedosto(t)
filesVideoOrPicture=Video- tai kuvatiedosto(t)
filesVideo=Videotiedosto(t)
fileVideo=Videotiedosto
fileMaster=Päätiedosto ja videon lisäystiedosto(t)

#grpChooseFunction
grpChooseFunction=Valitse toiminto
btnStartFunction=Aloita toiminto
btnPauseFunction=Keskeytä
btnResumeFunction=Jatka
btnStopRecording=Pysäytä tallennus
btnAddToRender=Lisää jonoon
btnDownload=Lataa video
btnCancel=Peruuta
lblFilter=Suodatin:
levels=Tasot:
shortest=lyhin
longest=pisin
aucun=ei mitään
mode=Tila:
audio=Ääni
video=Video

#grpDestination
output=Tulos
sameAsSource=Sama kuin lähde
caseSendMail=Lähetä yhteenveto sähköpostilla
textMail=Sähköpostiosoitteesi
caseStream=Ota suoratoisto käyttöön
caseLoop=Toista
caseOpenFolderAtEnd=Avaa kohdekansio lopussa
caseChangeFolder=Vaihda
caseDeleteSourceFile=Poista lähdetiedosto
aucune=Ei mitään
shutterEncodingCompleted=Shutter Encoder -koodaus valmis
shutterEncodingError=Shutter Encoder -koodausongelma
notEncoded=Ei voitu koodata.
isEncoded=On koodattu muotoon:

#grpProgression
lblEncodageEnCours=Ei käynnissä olevaa koodausta
waitingFiles=Odotetaan tiedostoja...
processCancelled=Prosessi peruutettu
processEnded=Prosessi valmis
grpProgression=Edistymisen tila
saveZip=Tallennetaan ZIP-tiedostoa
compression=Pakkaus käynnissä...
decompression=Purku käynnissä...
createBurnFiles=Luodaan tiedostoja polttoa varten...
babEncoding=Yhdistäminen käynnissä...
createOpatomFiles=Luodaan OP-Atom -tiedostoja
createAS10Format=Luodaan AS-10 -muotoa
caseRunInBackground=Työskentele toimettomuuden aikana
btnDisableAnimations=Poista animaatiot käytöstä
btnDisableSound=Poista lopetusääni käytöstä
btnDisableUpdate=Poista päivitykset käytöstä
btnDisableVideoPlayer=Poista videotoistin käytöstä
btnDisableMinimizedWindow=Poista pienennetty ikkuna käytöstä
btnPreventSleepMode=Estä lepotila
btnEmptyListAtEnd=Tyhjennä lista prosessin lopussa
btnEndingAction=Lopetustoiminto:
btnCustomFFmpegPath=Käytä paikallista ffmpeg:ää:
lblActionClose=sulje Shutter Encoder
lblActionShutdown=sammuta tietokone
analyzing=Analyysi käynnissä:
getVideoName=Haetaan videon otsikkoa
getAvailableFormats=Haetaan saatavilla olevia muotoja

#StatusBar
lblCrParPaul=tekijä Paul Pacifico
tempsRestant=Aikaa jäljellä:
tempsEcoule=Kulunut aika:
timePause=Aikaa jäljellä: Keskeytetty
firstPass=1. läpimeno
secondPass=2. läpimeno

#grpImageSequence
grpSequenceImage=Kuvasarja
caseActiverSequence=Aktivoi kuvasarja:
caseBlend=Kehyksen sekoitus: x0
blend=Kehyksen sekoitus:
caseMotionBlur=Lisää liikkeen sumennus

#grpImage
grpResolution=Kuva
caseCreateSequence=Luo kuvasarja videosta
lblInterpretation=Tulkitse videomateriaali:
caseRotate=Kierto:
caseAngle=Kulma:
caseMiror=Peilaa
posX=Sijainti X:
posY=Sijainti Y:

#grpImageFilter
grpFiltreImage=Suodatin
caseYear=Vuosi:
caseMonth=Kuukausi:
caseDay=Päivä:
caseFrom=Aikaväli:

#grpColorimetry
grpColorimetry=Värioppi
btnManage=Hallitse
caseLUTs=Käytä LUT:ia:
caseGamma=Gamma-taso:
caseLevels=Muunna tasot:
caseColormatrix=Muunna väriavaruus:
caseColorspace=Väriavaruus:

#grpInAndOut
cutUpper=Leikkaa
removeMode=Poista
splitMode=Jaa
enable=Ota käyttöön

#grpAudio
grpAudio=Ääniasetukset
mono=Mono
stereo=Stereo
codecCopy=Kopioi
noVideo=Ei videota
noAudio=Ei ääntä
custom=Mukautettu
caseAudioCodec=Muunna:
caseAudioOffset=Siirtymä:
caseKeepSourceTracks=Pidä lähteen ääniraidat
caseSampleRate=Vaihda näytteenottotaajuus:
caseMixAudio=Sekoita äänitiedostot:
caseSplitAudio=Erota ääniraidat:
caseConvertAudioFramerate=Muunna muodosta:

#grpOverlay
caseAddTimecode=Näytä
caseAddOverlay=Päällyste
caseShowTimecode=Näytä videon sisäinen aikakoodi
caseShowFileName=Näytä tiedostonimi
caseShowText=Näytä teksti:
lblTimecode=aikakoodi
lblFrameNumber=kehys nro

#grpTimecode
grpTimecode=Aikakoodi
caseSetTimecode=Aseta aikakoodi:
caseIncrementTimecode=Automaattinen lisäys
caseGenerateFromDate=Luo aikakoodi päivämäärästä
caseReadAudioTimecode=Lue äänen aikakoodi

#grpCorrections
grpCorrections=Korjaukset

#grpTransitions
grpTransitions=Siirtymät
lblVideoFadeIn=Videon häivytys sisään:
lblVideoFadeOut=Videon häivytys ulos:
lblAudioFadeIn=Äänen häivytys sisään:
lblAudioFadeOut=Äänen häivytys ulos:
white=valkoinen
black=musta

#grpAdvanced
grpAdvanced=Lisäominaisuudet
smoothExposure=Valotuksen tasoitus:
noiseSuppression=Kohinan vaimennus:
details=Yksityiskohdat:
accel=Laitteistokiihdytys
chooseLogo=Valitse vesileima
chooseSubtitles=Valitse tekstitystiedosto
preview=Esikatselu
caseForcerProgressif=Pakota progressiiviseksi
caseForcerEntrelacement=Pakota lomittainen
caseForcerInversion=Pakota kenttien kääntäminen
caseForcerDesentrelacement=Pakota lomitusten poisto:
caseForcerDAR=Pakota näyttö:
caseLimiter=Rajoita tuloste 16-235:een
caseCreateTree=Säilytä kansioiden hierarkia
casePreserveMetadata=Säilytä metadata
caseCookies=Käytä evästeitä selaimesta:
casePreserveSubs=Säilytä tekstitykset
caseCreateOPATOM=Luo muodossa
lblCreateOPATOM=muoto
caseOPATOM=Lähde OP-Atom-muodossa (P2, Canon XF, Sony...)
caseSubtitles=Lisää tekstitykset
caseStabilisation=Tasoita kuvaa
caseDeflicker=Poista välkkymistä
caseExposure=Valotuksen tasoitus: 0
caseBruit=Kohinan vaimennus: 0
caseBanding=Vähennä kaistoittumista
caseDetails=Yksityiskohdat: 0.0
caseDecimate=Poista toistuvat kehykset
caseConform=Sovita:
conformByReverse=Käänteinen
conformBySpeed=Nopeus
conformByDrop=Pudota
conformByBlending=Sekoitus
conformByInterpolation=Interpolaatio
conformBySlowMotion=Ultra-hidastus
caseAccel=Laitteistokiihdytys:
caseForceOutput=Pakota tuloste:
caseFastStart=Ota nopea käynnistys käyttöön
caseFastDecode=Ota nopea purku käyttöön
caseVarianceBoost=Ota varianssin tehostus käyttöön
caseAlpha=Ota alfakanava käyttöön
alphaStraight=suora
alphaPremultiply=esikerrottu
caseGOP=Aseta GOP:
caseFilmGrain=Aseta filmirae:
caseFilmGrainDenoise=Aseta filmiraekohinan poisto:
caseCABAC=Aseta entropiakoodaus CAVLC:ksi
caseChunks=Aseta palat:
caseDRC=Ota DRC käyttöön
caseForceLevel=Pakota profiili:
caseForcePreset=Pakota esiasetus:
caseForceTune=Pakota viritys:
caseForceSpeed=Pakota nopeus:
caseForceQuality=Pakota laatu:
caseLogo=Vesileima
caseAS10=Luo AS-10 -muoto:

#grpBitrate
grpBitrate=Bittinopeuden säätö
lblBitrateTimecode=Pituus:
lblBitrateSize=Mittakaava:
lblH=t
lblSec=s
lblPad=Sovita
lblCrop=Rajaa
lblStretch=Venytä
lblVideoBitrate=Videon bittinopeus:
lblValue=Arvo:
lblMaximumBitrate=Maksimi:
lblAudioBitrate=Äänen bittinopeus:
lblFromTo=kohteeseen:
lblBest=Paras
lblGood=Hyvä
lblWorst=Huonoin
source=Lähde
size=Tiedoston koko:
mo=MB
case2pass=2-kertainen
caseQMax=Max. laatu

#MenuItems
menuItemVisualiser=Näytä
menuItemSilentTrack=Lisää mykkä ääniraita
menuItemOuvrirDossier=Avaa tiedoston sijainti
menuItemInfo=Tiedosto(t)en tiedot...
menuItemRename=Nimeä tiedosto(t) uudelleen
menuItemInputDevice=Tallenna näyttö/laite
menuItemArborescence=Kopioi puurakenne
menuItemHash=Luo tiiviste
menuItemTempsTotal=Tiedosto(t)en kokonaispituus
menuItemPoids=Arvioitu tiedostokoko
menuItemGop=GOP-rakenne
menuItemFtp=Lähetä FTP-palvelimelle
menuItemZip=Luo ZIP-arkisto
menuItemUnzip=Pura arkisto
menuItemStartScan=Valvo kansiota
menuItemStopScan=Pysäytä tarkistus
menuItemOpenFolder=Avaa kansio
menuItemConsole=Näytä konsoli

#Functions
itemAITools=- Tekoälytyökalut:
itemNoConversion=- Ilman muunnosta:
itemAudioConversion=- Äänimuunnokset:
itemEditingCodecs=- Muokkauskoodekit:
itemOuputCodecs=- Tulostekoodikit:
itemBroadcastCodecs=- Lähetyskoodekit:
itemOldCodecs=- Vanhat koodekit:
itemArchiveCodecs=- Arkistointikoodekki:
itemBurnRip=- Poltto & purku:
itemImage=- Kuvan luonti:
itemAnalyze=- Analyysi:
itemDownload=- Lataus:
itemMyFunctions=Omat toiminnot...
functionCut=Leikkaa ilman uudelleenkoodausta
functionRewrap=Kääri uudelleen
functionConform=Sovita
functionExtract=Pura
functionInsert=Videolisäykset
functionSeparation=Äänierottelu
functionTranscribe=Äänitekstitys
functionTranslate=Käännä teksti
functionColorize=Väritä
functionBlurFaces=H\u00e4m\u00e4rt\u00e4\u00e4 kasvot
functionBackgroundRemover=Taustan poistaja
functionMerge=Yhdistä
functionReplaceAudio=Korvaa ääni
functionSubtitles=Tekstitys
functionPicture=Kuva
functionNormalization=Äänen normalisointi
functionSceneDetection=Leikkausten havaitseminen
functionBlackDetection=Mustan havaitseminen
functionOfflineDetection=Median offline-havainnointi
functionWeb=Web-video

#Console
btnSave=Tallenna
saveConsole=Tallenna konsoli
followLine=Vieritä tekstin mukana

#ColorImage
frameColorImage=Värin säätö
lblExposure=Valotus:
lblGamma=Gamma:
lblHighlights=Korostukset:
lblMediums=Keskisävyt:
lblShadows=Varjot:
lblWhite=Valkoiset:
lblBlack=Mustat:
lblBalance=Valkotasapaino:
lblHUE=Sävy:
lblContrast=Kontrasti:
lblGrain=Tasoitus/Terävöitys:
lblVignette=Vinjetointi:
lblSaturation=Kylläisyys:
lblVibrance=Eloisuus:
lblRGB=RGB:
lblRED=Punainen:
lblGREEN=Vihreä:
lblBLUE=Sininen:
lblZoom=Zoomaa:
intensity=Voimakkuus
red=Punainen
green=Vihreä
blue=Sininen
setAll=Kaikki
setHigh=Korkea
setMedium=Keskitaso
setLow=Matala

#CropImage
frameCropImage=Rajaus
btnApply=Käytä
lblWidth=Leveys:
lblHeight=Korkeus:
cantLoadFile=Tiedostoa ei voi ladata
error=Virhe

#CropVideo
wrongValue=Arvosi ei ole oikein
wrongFormat=Muotovirhe
lblPresets=Esiasetukset:

#CutDetection
frameDetectionCoupe=Leikkausten havaitseminen
btnAnalyse=Uusi analyysi
lblSensibility=Herkkyys:
btnEDL=Vie EDL:ään
saveEDL=Tallenna EDL
cut=leikkaus
fileCreated=Tiedoston luonti valmis
chooseFileName=Tiedostonimen valinta
lblEdit=Muokkaa poistonäppäimellä.
menuItemCopyTimecode=Kopioi aikakoodi
notProcessedFiles=Seuraavia tiedostoja ei voitu käsitellä:
encodingError=Koodausongelma

#RenderQueue
frameFileDeRendus=Renderöintijono
columnFile=Tiedosto
columnCommand=Komento
btnStartRender=Käynnistä renderöintijono
caseRunParallel=Suorita rinnakkain
destination=Kohde

#MyFunctions
frameFonctions=Omat toiminnot
lblSaveMac=Command + S tallentaaksesi toiminnon
lblSavePC=Ctrl + S tallentaaksesi toiminnon
lblDrop=Tai vedä toiminnot tähän
menuItemDelete=Poista toiminto
menuItemUpdate=Päivitä toiminto
menuItemLoad=Lataa toiminto

#Ftp
frameFtp=FTP-palvelin
lblFtp=FTP-osoite:
lblUser=Käyttäjä:
lblPassword=Salasana:
checkIdentity=Tarkista tunnuksesi
wrongIdentity=Virheelliset tunnukset
connectionRefused=Yhteyttä ei voitu muodostaa
connectionError=Ongelma yhdistettäessä palvelimeen
sendingFile=Lähetys käynnissä:
sendingSuccessful=Lähetys FTP-palvelimelle onnistui
sendingFailed=Lähetys FTP-palvelimelle epäonnistui
sendingCancelled=Lähetys FTP-palvelimelle peruutettiin
shutterMailFailed=Shutter Encoderin lähetys FTP:hen epäonnistui
shutterMailSuccessful=Shutter Encoderin lähetys FTP:hen onnistui
theFile=Tiedosto:
notSended=Ei voitu lähettää osoitteeseen:
isSended=On lähetetty osoitteeseen:
mailSuccessful=Sähköpostin lähetys onnistui
mailFailed=Sähköposti epäonnistui

#WeTransfer
lblMessage=Viesti:
lblYourMail=Sähköpostisi:
lblRecipient=Vastaanottaja(t):
sentFrom=Lähetetty osoitteesta www.shutterencoder.com
textTo=Osoitteet välilyönnillä erotettuna
casePlus=WeTransfer Plus -tili
sendingWTSuccessful=WeTransfer-lähetys onnistui
sendingWTFailed=WeTransfer-lähetys epäonnistui
sendingWTCancelled=WeTransfer-lähetys peruutettiin
link=WeTransfer-linkki:
linkError=WeTransfer-latausvirhe
linkCopied=WeTransfer-linkki kopioitu leikepöydälle

#GOP
analyzeOf=Tiedoston analyysi:
of=of

#Informations
frameInformations=Tiedot
lblWait=Analyysi käynnissä, odota...

#VideoPlayer
btnCancel=Peruuta
casePlaySound=Kehys kerrallaan -ääni
caseVuMeter=Vu-mittari
caseGPU=Käytä GPU:ta
caseTcInterne=Näytä videon aikakoodi
lblDuree=Kesto:
lblTotalFrames=kehystä

#Logo
frameLogo=Lisää vesileima
caseSafeArea=Turva-alue
lblSize=Koko:
lblOpacity=Läpinäkyvyys:

#MiniWindow
lblEnCours=Ei tiedostoja käynnissä

#Settings
frameSettings=Asetukset
lblThreads=Aseta käytettävien säikeiden määrä (0 = auto):
lblScreenRecord=Aseta näytön tallennuksen kuvataajuus:
lblInputDevice=Aseta syöttölaitteen kuvataajuus:
lblImageToVideo=Aseta still-kuvan kesto:
lblFrames=kehystä
btnSetBab=Käsittele tiedostolista yhdistämisenä
btnOpenGOP=Aseta toiminto Open-GOP:ksi
casePrefix=Lisää etuliite:
btnExtension=Lisää pääte:
caseSubFolder=Luo alikansio:
btnExclude=Poissulje päätteet:
btnHidePath=Piilota tiedostolistan polku
btnLoadPreset=Lataa käynnistyksessä:
btnWaitFileComplete=Odota automaattisesti, että tiedosto on valmis
toDefault=oletus:
lastUsed=Viimeksi käytetty
lblGpuDecoding=GPU-purku:
lblGpuFiltering=GPU-suodatus:
lblStrictMode=Aseta tiukka tila:
lblScaleMode=Aseta skaalaustila:
btnNoUpscale=Älä skaalaa ylöspäin pienempiä resoluutioita
btnPreviewOutput=Esikatsele lopullista tulosteen laatua (kokeellinen)
lblSyncMode=Aseta kuvataajuustila:
lblLanguage=Aseta kieli:
lblTheme=Aseta korostusväri:

#RenameWindow
frameRenommage=Nimeä tiedosto(t) uudelleen
btnLimit=Rajoita merkkien määrä:
btnIncrementer=Lisää alkaen:
lblRemplacer=Korvaa:
lblPar=Kohteella:
lblExemple=Esimerkki:
renommer=Nimeä uudelleen
btnAjouterAvant=Lisää ennen:
btnAjouterApres=Lisää jälkeen:
convertToLower=Pienet kirjaimet
convertToUpper=Isot kirjaimet
removeSpecialCharacters=Poista erikoismerkit
filesAlreadyExists=Tiedosto(t) on jo olemassa

#Subtitles
lblTimeline=Aikajana
lblSubtitlesPosition=Y:
frameAddSubtitles=Lisää tekstitykset
lblFont=Fontti:
lblsubtitleNumber=Tekstitys nro
lblColor=Väri:
lblBackgroundOff=Ääriviiva
lblBackgroundOn=Tausta
btnG=T
frameSubtitles=Tekstitys
integrateSRT=Haluatko lisätä tekstitykset videoon?
subtitles=Tekstitykset
lblTexte=Teksti:
lblHelp=Ohje
subtitlesLower=tekstitys(tä)
btnAdd=Lisää
btnModify=Muokkaa
btnDelete=Poista
deleteConfirmation=Vahvista poisto?
subtitlesDelete=Tekstityksen poistaminen
btnDebut=Alku
btnFin=Loppu
lblOffset=Siirtymä:
caseShowWaveform=Näytä aaltomuoto
txtShortcuts=Käytä Tab-näppäintä vaihtaaksesi aikajanan ja tekstin välillä:\r\n\r\n- Alku/Loppu: I ja O\r\n- Seuraava/Edellinen tekstitys: nuoli ylös/alas\r\n- Siirry eteenpäin/taaksepäin yhdellä kehyksellä: nuoli vasemmalle/oikealle\n- Taaksepäin/eteenpäin 10 kehystä: J ja L\r\n- Näytä/Piilota aaltomuoto: W\r\n- Toista/Keskeytä: välilyönti tai K\r\n- Leikkaa: C\r\n- Poista: askelpalautin tai del.\r\n- Lisää: enter\r\n\r\nPikakomennot käytettävissä CTRL-näppäin pohjassa:\r\n\r\n- Kursivoitu: I\r\n- Lihavoitu: B\r\n
chooseColor=Valitse väri
subtitlesFileError=Virheellinen tekstitystiedosto
invalidSubtitles=Tiedostosi on oltava SRT/VTT/SSA/ASS/SCC

#SubtitlesEdit
frameSubtitlesEdit=Muokkaa kaikkia tekstejä

#Equalizer
frameEqualizer=Taajuuskorjain

#WebVideo
lblURL=URL:
panelWebVideo=Lataa
frameVideoWeb=Videon URL-osoite
videoUrl=Videon URL
textURL=http://www.yourvideo.com
caseUser=Käyttäjä:
casePass=Salasana:
caseVideoPass=Videon salasana:
update=Päivitetään
MenuItemPaste=Liitä
invalidUrl=Tarkista URL-osoitteesi ja/tai käyttäjätunnuksesi/salasanasi
downloadError=Latausongelma
lblQualit=Laatu:
caseMP3=Muunna MP3:ksi
caseWAV=Muunna WAV:ksi
convertToWAV=Muunna wav:ksi
convertToMP3=Muunna mp3:ksi

#Update
lblNewVersion=Ladataan uutta versiota...
frameUpdate=Päivitä Shutter Encoder
wantToDownload=Haluatko ladata sen?
updateAvailable=Päivitys saatavilla
installNewVersion=Haluatko asentaa uuden version?
downloadEnded=Lataus valmis
downloadCancelled=Lataus peruutettu
downloadStopped=Lataus on keskeytetty
downloadFailed=Lataus epäonnistui!
downloadError=Latausongelma
downloadModel=Valitse tekoälymalli

#Tooltips
newInstance=Uusi instanssi
rightClick=Hiiren oikea painike käytettävissä...
tooltipMixAudio=Jos lähde on mono -> parilliset tiedostot vasen, parittomat oikea
tooltipProgressif=Poistaaksesi lomituksen videosta käytä siihen liittyvää ruutua / Yksinään tarkistettuna tämä ruutu mahdollistaa siirtymisen PsF:stä progressiiviseksi
tooltipEntrelacement=Jos lähde on 50p (59,94p,60p) lomitus 50i:ksi (59,94i,60i)
tooltipCreateOpatom=Vedä .mdb-tiedosto koriisi Avidin skannattua tiedostot
tooltipDetails=Hyödyllinen poistamaan aliasointia videosta

#Messages
colon=:
fps=fps
yes=Kyllä
no=Ei
yesToAll=Kyllä kaikille
noToAll=Ei kaikille
btnKeep=Pidä
btnSkip=Ohita
btnOverwrite=Korvaa
caseApplyToAll=Käytä kaikkiin
cutOnKeyframesOnly=Tämä toiminto leikkaa vain avainkehyksissä
noAccel=Ei laitteistokiihdytystä saatavilla\r\nVarmista, että ajurisi ovat ajan tasalla!
replaceAudioMissing=Tarvitset vähintään yhden videoleikkeen ja yhden äänileikkeen listassa
missingElement=Puuttuva elementti
selectedFiles=Valitut tiedosto(t)
ChooseDifferentFolder=Valitse eri kohdekansio
sameFolder=Tarkistus- ja kohdekansio ovat samat!
scanIncompatible=Yhteensopimaton toiminto valvotun kansion kanssa
scanActivated=Valvottu kansio aktivoitu
addInputDevice=Lisää syöttölaite?
incompatibleInputDevice=Yhteensopimaton syöttölaite
approximativeWeight=Arvioitu paino
chooseFolderToCopy=Valitse kopioitava kansio
chooseDestinationFolder=Valitse kohdekansio
sameFolders=Kansiot eivät voi olla samat
copyError=Kopiointivirhe
copyFinished=Kopiointi valmis
treeCopy=Puukopio
chooseScanFolder=Valitse tarkistettava kansio
dragFolderToList=Vedä kansio listaan
dragFolderToDestination=Vedä kansio kohde-osioon
previewNotAvailable=Esikatselu ei saatavilla
areYouSure=Oletko varma?
restart=Käynnistä sovellus uudelleen?
shutdown=Sammuta 60 sekunnissa
chooseExtension=Sinun on valittava pääte
extensionError=Pääteongelma
resume=Jatka
isAlreadyStereo=On jo stereona
cantSplitAudio=Ei voitu erottaa raitoja
saveResult=Haluatko tallentaa tuloksen?
analyzeEnded=Analyysi valmis
noErrorDetected=Ei virheitä havaittu
noDVD=Asemassa ei ole DVD:tä
DVDMissing=DVD puuttuu
totalTime=Kokonaiskesto:
totalTimeFiles=Tiedosto(t)en kokonaiskesto
chooseResolution=Valitse resoluutio:
resolution=Resoluutio
to=kohteeseen
addFileToList=Lisää tiedosto listaan
noFileInList=Ei tiedostoja listassa
noFile=Ei tiedostoa
eraseFile=Haluatko korvata tiedoston?
File=Tiedosto
alreadyExist=On jo olemassa
cantAnalyzeGop=Ei voitu analysoida GOP-rakennetta
analyzeError=Analyysiongelma
shortTerm=Ei lyhytaikaista korkeampaa kuin -16 LUFS
multitrack=Moniraita havaittu
ChooseMultitrack=Valitse analysoitavat raidat:
opatomNoSound=Ääntä ei säilytetä OP-Atomissa!
chooseSoftware=Valitse ohjelmistosi
chooseSubsIntegration=Mitä haluat tehdä?
subtitlesBurn=Polta
subtitlesEmbed=Upota
mayNotWorkWithGOP=Ei välttämättä toimi kunnolla GOP-pohjaisten koodekkien kanssa
invalidCharacter=sisältää virheellisiä merkkejä, se ei välttämättä toimi kunnolla
sourceFile=Valitse lähdetiedosto
ffmpeg=FFmpeg:
shutterTranscriberRequired=Tämä ominaisuus vaatii Shutter Transcriberin.
shutterAnonymizerRequired=T\u00e4m\u00e4 ominaisuus edellytt\u00e4\u00e4 Shutter Anonymizer -sovellusta.
additionalFiles=Lisätiedostoja tarvitaan.
downloadingAIModel=Ladataan tekoälymallia

#OTHER
command=Komento:
saveSettings=Tallennetaan asetuksia
